# Generated by Django 3.0.6 on 2020-05-29 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_status', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('title', models.CharField(max_length=2000)),
                ('video_ss', models.FileField(default=None, upload_to='blog/staticfiles/')),
                ('videofile', models.FileField(upload_to='blog/staticfiles/')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Chapters')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_status', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=2000)),
                ('docs', models.FileField(upload_to='blog/staticfiles')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Chapters')),
            ],
        ),
        migrations.AddField(
            model_name='chapters',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Course'),
        ),
    ]
