# Generated by Django 3.0.6 on 2020-05-29 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_course_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
    ]
