# Generated by Django 3.0.6 on 2020-05-31 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_course_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Videos'),
        ),
    ]
