# Generated by Django 3.0.6 on 2020-05-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200531_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='docs',
            field=models.FileField(upload_to='blog/staticfiles/'),
        ),
    ]
